### ISSUE TITLE
changes to clean_outcome_label cause small bug

### ISSUE THREAD

**Issue by msalganik** [atkindel/ffc_replication#5]
for (row in 1:6) {
   table_to_print[row, "outcome"] <- clean_outcome_label(table_to_print[row, "outcome"])
}

Causes this error:
Error in x[[jj]][iseq] <- vjj : replacement has length zero

I'm disabling this because it is just to clean up the label.  We can refactor later.

**Comment by atkindel** [comment]
Resolved by commit 005228c
